apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "infrastructure-health-api.fullname" . }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "infrastructure-health-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s